# Generated by Django 5.1.6 on 2025-02-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка категории')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('color_name', models.CharField(default='Белый', max_length=20, verbose_name='Название цвета')),
                ('color_code', models.CharField(default='#ffffff', max_length=20, verbose_name='Код цвета')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Слаг товара')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='digitalstore.category', verbose_name='Категория')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalstore.productmodel', verbose_name='Модель товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='GalleryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='digitalstore.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото Товара',
                'verbose_name_plural': 'Фото Товаров',
            },
        ),
    ]
