# Generated by Django 5.1.6 on 2025-02-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0002_remove_product_description_airconditioner_laptop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditioner',
            name='product',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='refrigerator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='product',
        ),
    ]
