# Generated by Django 5.1.6 on 2025-02-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0003_remove_airconditioner_product_remove_laptop_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconditioner',
            name='product',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalstore.product'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='product',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalstore.product'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='digitalstore.product'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='product',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalstore.product'),
        ),
        migrations.AddField(
            model_name='tv',
            name='product',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalstore.product'),
        ),
    ]
