# Generated by Django 5.1.6 on 2025-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0004_airconditioner_product_laptop_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='refrigerator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ac_cooling_power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность охлаждения'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_heating_power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность обогрева'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_noise_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень шума'),
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аккумулятор'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage_area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Площадь размещения'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры (ВxШxГ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс энергопотребления'),
        ),
        migrations.AddField(
            model_name='product',
            name='freezer_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем морозильной камеры (л)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объем холодильной камеры (л)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_compressor_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип компрессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_temperature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Максимальная температура'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_temperature',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Минимальная температура'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер экрана (диагональ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_technology',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Технология экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_refresh_rate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Частота обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_smart',
            field=models.BooleanField(default=False, verbose_name='Smart TV'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.DeleteModel(
            name='AirConditioner',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='Refrigerator',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
        migrations.DeleteModel(
            name='TV',
        ),
    ]
