# Generated by Django 5.1.6 on 2025-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0005_remove_laptop_product_remove_product_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_name',
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гарантия'),
        ),
    ]
