# Generated by Django 5.1.6 on 2025-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0007_productmodel_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tv_smart',
            field=models.CharField(default=False, max_length=20, verbose_name='Smart TV'),
        ),
    ]
