# Generated by Django 5.1.6 on 2025-03-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0008_alter_product_tv_smart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tv_smart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Smart TV'),
        ),
    ]
