# Generated by Django 5.1.6 on 2025-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0009_alter_product_tv_smart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ёмкость аккумулятора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес (г, кг)'),
        ),
    ]
