# Generated by Django 5.1.6 on 2025-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0012_region_customer_order_orderproduct_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.TextField(max_length=100, verbose_name='Город доставки'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='region',
            field=models.TextField(max_length=100, verbose_name='Регион доставки'),
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставок'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='home',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
