# Generated by Django 5.1.6 on 2025-03-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0015_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.CreateModel(
            name='SaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('total_price', models.FloatField(default=0, verbose_name='Сумма заказа')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('completed', models.BooleanField(default=False, verbose_name='Статус заказа')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalstore.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Сохранить заказ',
                'verbose_name_plural': 'Сохраннёные заказы',
            },
        ),
        migrations.CreateModel(
            name='SaveOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, verbose_name='Название товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('price', models.FloatField(default=0, verbose_name='Цена товара')),
                ('product_slug', models.CharField(max_length=300, verbose_name='Слаг товара')),
                ('price_in', models.FloatField(verbose_name='На сумму')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Фото товара')),
                ('color_name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='digitalstore.saveorder')),
            ],
            options={
                'verbose_name': 'Сохранить товар в заказ',
                'verbose_name_plural': 'Сохраннёные товары заказы ',
            },
        ),
    ]
