# Generated by Django 5.1.6 on 2025-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0016_alter_profile_options_saveorder_saveorderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_cooling_power_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность охлаждения'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_cooling_power_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность охлаждения'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_heating_power_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность обогрева'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_heating_power_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность обогрева'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_noise_level_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень шума'),
        ),
        migrations.AddField(
            model_name='product',
            name='ac_noise_level_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень шума'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_en',
            field=models.CharField(default='Белый', max_length=20, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_ru',
            field=models.CharField(default='Белый', max_length=20, null=True, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_class_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс энергопотребления'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_class_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс энергопотребления'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_compressor_type_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип компрессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='fridge_compressor_type_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип компрессора'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='front_camera_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_camera_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_system_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_technology_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Технология экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_technology_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Технология экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_refresh_rate_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Частота обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_refresh_rate_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Частота обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_resolution_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_resolution_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_smart_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Smart TV'),
        ),
        migrations.AddField(
            model_name='product',
            name='tv_smart_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Smart TV'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='saveorderproduct',
            name='color_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='saveorderproduct',
            name='color_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='saveorderproduct',
            name='product_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='saveorderproduct',
            name='product_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название товара'),
        ),
    ]
