# Generated by Django 5.1.6 on 2025-03-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0018_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
