# Generated by Django 5.1.6 on 2025-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0019_rename_phone_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_en',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_ru',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city_en',
            field=models.TextField(max_length=100, null=True, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city_ru',
            field=models.TextField(max_length=100, null=True, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='comment_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='comment_ru',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region_en',
            field=models.TextField(max_length=100, null=True, verbose_name='Регион доставки'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region_ru',
            field=models.TextField(max_length=100, null=True, verbose_name='Регион доставки'),
        ),
    ]
