# Generated by Django 5.1.6 on 2025-03-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0020_rename_phone_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
