# Generated by Django 5.1.6 on 2025-03-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalstore', '0021_rename_avatar_profile_image_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
